// <auto-generated />
using System;
using DeskCloudCompare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskCloudCompare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405211107_AddCountryFileExceptions")]
    partial class AddCountryFileExceptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanonicalFrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDxdb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinancialData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalFrameworkId");

                    b.ToTable("CanonicalFiles");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFramework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Category")
                        .IsUnique();

                    b.ToTable("CanonicalFrameworks");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryEntry", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("CountryEntries");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFileException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanonicalFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalFileId", "CountryCode")
                        .IsUnique();

                    b.ToTable("CountryFileExceptions");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFilePresence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinaryHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonicalFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalFileId");

                    b.ToTable("CountryFilePresences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFrameworkPresence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonicalFrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalFrameworkId");

                    b.ToTable("CountryFrameworkPresences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryManagerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterCountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CountryManagerSettings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.DxdbCsvMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CsvFilePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DxdbFilePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DxdbCsvMappings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CsvColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DxdbColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DxdbCsvMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DxdbTableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKeyField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DxdbCsvMappingId");

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FolderPresets");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPresetSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderTypeId");

                    b.HasIndex("PresetId");

                    b.ToTable("FolderPresetSlots");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FolderTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canonical"
                        });
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PathTranslationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplaceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromTypeId");

                    b.HasIndex("ToTypeId");

                    b.ToTable("PathTranslationRules");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PresetExclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.ToTable("PresetExclusions");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.SpecialFileRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNamePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SpecialFileRules");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFile", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.CanonicalFramework", "CanonicalFramework")
                        .WithMany("Files")
                        .HasForeignKey("CanonicalFrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalFramework");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFileException", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.CanonicalFile", "CanonicalFile")
                        .WithMany()
                        .HasForeignKey("CanonicalFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalFile");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFilePresence", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.CanonicalFile", "CanonicalFile")
                        .WithMany("Presences")
                        .HasForeignKey("CanonicalFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalFile");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFrameworkPresence", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.CanonicalFramework", "CanonicalFramework")
                        .WithMany("Presences")
                        .HasForeignKey("CanonicalFrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalFramework");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FieldMapping", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.DxdbCsvMapping", "DxdbCsvMapping")
                        .WithMany("FieldMappings")
                        .HasForeignKey("DxdbCsvMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DxdbCsvMapping");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPresetSlot", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderType", "FolderType")
                        .WithMany("Slots")
                        .HasForeignKey("FolderTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeskCloudCompare.Models.FolderPreset", "Preset")
                        .WithMany("Slots")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderType");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PathTranslationRule", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderType", "FromType")
                        .WithMany("FromRules")
                        .HasForeignKey("FromTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskCloudCompare.Models.FolderType", "ToType")
                        .WithMany("ToRules")
                        .HasForeignKey("ToTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromType");

                    b.Navigation("ToType");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PresetExclusion", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderPreset", "Preset")
                        .WithMany("Exclusions")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFile", b =>
                {
                    b.Navigation("Presences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFramework", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Presences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.DxdbCsvMapping", b =>
                {
                    b.Navigation("FieldMappings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPreset", b =>
                {
                    b.Navigation("Exclusions");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderType", b =>
                {
                    b.Navigation("FromRules");

                    b.Navigation("Slots");

                    b.Navigation("ToRules");
                });
#pragma warning restore 612, 618
        }
    }
}
