// <auto-generated />
using DeskCloudCompare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DeskCloudCompare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411120000_SeedCloudUkiFrameworkSuffixRules")]
    partial class SeedCloudUkiFrameworkSuffixRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
#pragma warning restore 612, 618
        }
    }
}
