// <auto-generated />
using DeskCloudCompare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DeskCloudCompare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411110000_SeedMonthlyManpackAlias")]
    partial class SeedMonthlyManpackAlias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DeskCloudCompare.Models.MasterFileAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath", "ActualFileName")
                        .IsUnique();

                    b.ToTable("MasterFileAliases");
                });
#pragma warning restore 612, 618
        }
    }
}
