// <auto-generated />
using System;
using DeskCloudCompare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskCloudCompare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FolderPresets");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPresetSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderTypeId");

                    b.HasIndex("PresetId");

                    b.ToTable("FolderPresetSlots");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FolderTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canonical"
                        });
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PathTranslationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplaceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromTypeId");

                    b.HasIndex("ToTypeId");

                    b.ToTable("PathTranslationRules");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPresetSlot", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderType", "FolderType")
                        .WithMany("Slots")
                        .HasForeignKey("FolderTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeskCloudCompare.Models.FolderPreset", "Preset")
                        .WithMany("Slots")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderType");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PathTranslationRule", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderType", "FromType")
                        .WithMany("FromRules")
                        .HasForeignKey("FromTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskCloudCompare.Models.FolderType", "ToType")
                        .WithMany("ToRules")
                        .HasForeignKey("ToTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromType");

                    b.Navigation("ToType");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPreset", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderType", b =>
                {
                    b.Navigation("FromRules");

                    b.Navigation("Slots");

                    b.Navigation("ToRules");
                });
#pragma warning restore 612, 618
        }
    }
}
