// <auto-generated />
using System;
using DeskCloudCompare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskCloudCompare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanonicalFrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDxdb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinancialData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalFrameworkId");

                    b.ToTable("CanonicalFiles");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFramework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Category")
                        .IsUnique();

                    b.ToTable("CanonicalFrameworks");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryEntry", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("CountryEntries");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFileException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameworkCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameworkName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkName", "FrameworkCategory", "RelativePath", "CountryCode")
                        .IsUnique();

                    b.ToTable("CountryFileExceptions");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFilePresence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinaryHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonicalFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalFileId");

                    b.ToTable("CountryFilePresences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFrameworkPresence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualFolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanonicalFrameworkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalFrameworkId");

                    b.ToTable("CountryFrameworkPresences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryManagerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterCountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CountryManagerSettings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.DxdbCsvMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CsvFilePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DxdbFilePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DxdbCsvMappings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CsvColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DxdbColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DxdbCsvMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DxdbTableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKeyField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DxdbCsvMappingId");

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FolderPresets");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPresetSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderTypeId");

                    b.HasIndex("PresetId");

                    b.ToTable("FolderPresetSlots");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FolderTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canonical"
                        });
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FrameworkManagerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FrameworkManagerSettings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterCanonicalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDxdb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinancialData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeGroup", "RelativePath")
                        .IsUnique();

                    b.ToTable("MasterCanonicalFiles");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterFileAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath", "ActualFileName")
                        .IsUnique();

                    b.ToTable("MasterFileAliases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualFileName = "Director Certificates.xlsx",
                            CanonicalFileName = "Director Certificates.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 2,
                            ActualFileName = "Partner Certificates.xlsx",
                            CanonicalFileName = "Director Certificates.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 3,
                            ActualFileName = "Proprietor Certificates.xlsx",
                            CanonicalFileName = "Director Certificates.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 4,
                            ActualFileName = "Trustee Certificates.xlsx",
                            CanonicalFileName = "Director Certificates.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 5,
                            ActualFileName = "Member Certificates.xlsx",
                            CanonicalFileName = "Director Certificates.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 6,
                            ActualFileName = "Directors Minutes-Resolution.xlsx",
                            CanonicalFileName = "Directors Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 7,
                            ActualFileName = "Partner Minutes-Resolution.xlsx",
                            CanonicalFileName = "Directors Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 8,
                            ActualFileName = "Proprietor Minutes-Resolution.xlsx",
                            CanonicalFileName = "Directors Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 9,
                            ActualFileName = "Trustee Minutes-Resolution.xlsx",
                            CanonicalFileName = "Directors Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 10,
                            ActualFileName = "Member Minutes-Resolution.xlsx",
                            CanonicalFileName = "Directors Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 11,
                            ActualFileName = "Shareholder Minutes-Resolution.xlsx",
                            CanonicalFileName = "Shareholder Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 12,
                            ActualFileName = "Partner Minutes-Resolution2.xlsx",
                            CanonicalFileName = "Shareholder Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 13,
                            ActualFileName = "Proprietor Minutes-Resolution2.xlsx",
                            CanonicalFileName = "Shareholder Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 14,
                            ActualFileName = "Trustee Minutes-Resolution2.xlsx",
                            CanonicalFileName = "Shareholder Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        new
                        {
                            Id = 15,
                            ActualFileName = "Member Minutes-Resolution2.xlsx",
                            CanonicalFileName = "Shareholder Minutes-Resolution.xlsx",
                            FolderPath = "Documents\\DraftworX Files"
                        },
                        // Financial statement files — Financial Data\DraftworX Files
                        // IFRS type group: consolidation + entity variants → IFRS+ Financials.xlsx
                        new { Id = 16, ActualFileName = "IFRS+ Consolidation.xlsx",          CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 17, ActualFileName = "IFRS SME+ Consolidation.xlsx",      CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 18, ActualFileName = "IFRS Consolidation.xlsx",           CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 19, ActualFileName = "ASPE+ Financials.xlsx",             CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 20, ActualFileName = "IFRS SME+ Financials.xlsx",         CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 21, ActualFileName = "IFRS Financials.xlsx",              CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 22, ActualFileName = "FRS101 Financials.xlsx",            CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 23, ActualFileName = "Body Corp+ Financials.xlsx",        CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 24, ActualFileName = "CC+ Financials.xlsx",               CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 25, ActualFileName = "NPC+ Financials.xlsx",              CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 26, ActualFileName = "NPO+ Financials.xlsx",              CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 27, ActualFileName = "Partnership+ Financials.xlsx",      CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 28, ActualFileName = "School+ Financials.xlsx",           CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 29, ActualFileName = "Sole Prop+ Financials.xlsx",        CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 30, ActualFileName = "Trust+ Financials.xlsx",            CanonicalFileName = "IFRS+ Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" },
                        // FRS type group: consolidation + entity variants → FRS102 Financials.xlsx
                        new { Id = 31, ActualFileName = "FRS102 Consolidation.xlsx",         CanonicalFileName = "FRS102 Financials.xlsx",           FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 32, ActualFileName = "FRS102(1A) Consolidation.xlsx",     CanonicalFileName = "FRS102 Financials.xlsx",           FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 33, ActualFileName = "FRS102(1A) Financials.xlsx",        CanonicalFileName = "FRS102 Financials.xlsx",           FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 34, ActualFileName = "FRS105 Financials.xlsx",            CanonicalFileName = "FRS102 Financials.xlsx",           FolderPath = "Financial Data\\DraftworX Files" },
                        // FRS type group → Partnership / Sole Prop / LLP
                        new { Id = 35, ActualFileName = "Partnership(1A) Financials.xlsx",   CanonicalFileName = "Partnership Financials.xlsx",      FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 36, ActualFileName = "Partnership(105) Financials.xlsx",  CanonicalFileName = "Partnership Financials.xlsx",      FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 37, ActualFileName = "Sole Prop(1A) Financials.xlsx",     CanonicalFileName = "Sole Prop Financials.xlsx",        FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 38, ActualFileName = "Sole Prop(105) Financials.xlsx",    CanonicalFileName = "Sole Prop Financials.xlsx",        FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 39, ActualFileName = "LLP(1A) Financials.xlsx",           CanonicalFileName = "LLP Financials.xlsx",              FolderPath = "Financial Data\\DraftworX Files" },
                        // Legacy type group: Afrikaans → canonical English name
                        new { Id = 40, ActualFileName = "Body Corporate_Afrikaans.xlsx",     CanonicalFileName = "Body Corporate Financials.xlsx",   FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 41, ActualFileName = "Close Corporation_Afrikaans.xlsx",  CanonicalFileName = "Close Corporation Financials.xlsx",FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 42, ActualFileName = "IFRS SME_Afrikaans.xlsx",           CanonicalFileName = "IFRS SME Financials.xlsx",         FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 43, ActualFileName = "Partnership_Afrikaans.xlsx",        CanonicalFileName = "Partnership Financials.xlsx",      FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 44, ActualFileName = "Sole Proprietor_Afrikaans.xlsx",    CanonicalFileName = "Sole Proprietor Financials.xlsx",  FolderPath = "Financial Data\\DraftworX Files" },
                        new { Id = 45, ActualFileName = "Trust Financials _Afrikaans.xlsx",  CanonicalFileName = "Trust Financials.xlsx",            FolderPath = "Financial Data\\DraftworX Files" });
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterFileException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameworkCanonicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeGroup", "RelativePath", "FrameworkCanonicalName")
                        .IsUnique();

                    b.ToTable("MasterFileExceptions");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterFilePresence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BinaryHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("MasterCanonicalFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MasterFrameworkEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MasterFrameworkEntryId");

                    b.HasIndex("MasterCanonicalFileId", "MasterFrameworkEntryId")
                        .IsUnique();

                    b.ToTable("MasterFilePresences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterFrameworkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName")
                        .IsUnique();

                    b.ToTable("MasterFrameworkEntries");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.SubFrameworkFileException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameworkCanonicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubGroup", "RelativePath", "FrameworkCanonicalName")
                        .IsUnique();

                    b.ToTable("SubFrameworkFileExceptions");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PathTranslationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplaceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromTypeId");

                    b.HasIndex("ToTypeId");

                    b.ToTable("PathTranslationRules");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PresetExclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.ToTable("PresetExclusions");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.SpecialFileRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNamePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SpecialFileRules");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFile", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.CanonicalFramework", "CanonicalFramework")
                        .WithMany("Files")
                        .HasForeignKey("CanonicalFrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalFramework");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFilePresence", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.CanonicalFile", "CanonicalFile")
                        .WithMany("Presences")
                        .HasForeignKey("CanonicalFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalFile");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CountryFrameworkPresence", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.CanonicalFramework", "CanonicalFramework")
                        .WithMany("Presences")
                        .HasForeignKey("CanonicalFrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalFramework");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FieldMapping", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.DxdbCsvMapping", "DxdbCsvMapping")
                        .WithMany("FieldMappings")
                        .HasForeignKey("DxdbCsvMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DxdbCsvMapping");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPresetSlot", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderType", "FolderType")
                        .WithMany("Slots")
                        .HasForeignKey("FolderTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeskCloudCompare.Models.FolderPreset", "Preset")
                        .WithMany("Slots")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderType");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterFilePresence", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.MasterCanonicalFile", "MasterCanonicalFile")
                        .WithMany("Presences")
                        .HasForeignKey("MasterCanonicalFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskCloudCompare.Models.MasterFrameworkEntry", "MasterFrameworkEntry")
                        .WithMany("FilePresences")
                        .HasForeignKey("MasterFrameworkEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCanonicalFile");

                    b.Navigation("MasterFrameworkEntry");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PathTranslationRule", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderType", "FromType")
                        .WithMany("FromRules")
                        .HasForeignKey("FromTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskCloudCompare.Models.FolderType", "ToType")
                        .WithMany("ToRules")
                        .HasForeignKey("ToTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromType");

                    b.Navigation("ToType");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.PresetExclusion", b =>
                {
                    b.HasOne("DeskCloudCompare.Models.FolderPreset", "Preset")
                        .WithMany("Exclusions")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFile", b =>
                {
                    b.Navigation("Presences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.CanonicalFramework", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Presences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.DxdbCsvMapping", b =>
                {
                    b.Navigation("FieldMappings");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderPreset", b =>
                {
                    b.Navigation("Exclusions");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.FolderType", b =>
                {
                    b.Navigation("FromRules");

                    b.Navigation("Slots");

                    b.Navigation("ToRules");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterCanonicalFile", b =>
                {
                    b.Navigation("Presences");
                });

            modelBuilder.Entity("DeskCloudCompare.Models.MasterFrameworkEntry", b =>
                {
                    b.Navigation("FilePresences");
                });
#pragma warning restore 612, 618
        }
    }
}
